<?php
/**  * Created by PhpStorm.
 * User: Hadesker - HienNV
 * Date: 9/12/2018
 * Time: 3:57 PM
 */

return [
    'learn_more'=>'Learn More',
    'sitemap'=>'Sitemap',
    'privacy_policy'=>'Privacy Policy',
    'top'=>'TOP',
    'back'=>'Back',
    'bwid'=>'BW Industrial Development JSC',
    'we_are'=>'We are',
    'coming_soon'=>'Coming soon',
    'contact_after'=>'Please come back later',
    'our_company'=>'Our company',
    'vision_values'=>'Vision & Values',
    'core_management_team'=>'Core management team',
    'milestones'=>'Milestones',
    'fund_management'=>'Our partners',
    'our_businesses'=>'Our businesses',
    'business_model'=>'Business model',
    'property_type'=>'Property type',
    'our_presence'=>'Our presence',
    'property_leasing'=>'Property leasing',
    'media_center'=>'Media center',
    'careers'=>'Careers',
    'search'=>'Search',
    'looking_for'=>'What are you looking for',
    'search_result_for'=>'Search results for',
    'search_for'=>'Search for',
    'all'=>'All',
    'our_partner'=>'Our customers',
    'news'=>'News',
    'gallery'=>'Gallery',
    'photo'=>'Photo',
    'video'=>'Video',
    'current_opening'=>'Career opportunities',
    'property_for_lease'=>'Property for lease',
    'view_all'=>'View all',
    'news_bw'=>'BW Industrial news',
    'news_investor'=>'Market news',
    'enter_job_title'=>'Enter job title',
    'department'=>'Department',
    'locations'=>'Locations',
    'load_more'=>'Load more',
    'select_property_type'=>'Select Property Type',
    'select_region'=>'Select Region',
    'clear'=>'Clear',
    'related_videos'=>'Related videos',
    'related_photos'=>'Related photos',
    'coppy_right' => '© 2021 Masan High-Tech Materials. By using this site you agree that we can place cookies on your device. View our privacy policy for details.',
    'mht-in-the-news' =>'Press release',
    'mht_in_the_news' =>'MHT in the news',
    'annual_reports' =>'Annual report',
    'corporate_documents' =>'Corporate Documents ',
    'financial_information' =>'Financial Information',
    'corporate_announcements' => 'Corporate Announcements',
    'media_center' =>'Media center',
    'all_product' =>'All Products',
    'south'=>'South',
    'north'=>'North',

    'learn_about_other_properties'=>'Learn about other Properties',
    'project_features' => 'Project Features',
    'project_pictures' => 'Pictures'
];